# utils/session_state.py
def init_state(st):
    # quiz data generated by LLM
    if "quiz_data" not in st.session_state:
        st.session_state.quiz_data = None

    # user answers (indexes 0-3 as chosen)
    if "quiz_answers" not in st.session_state:
        st.session_state.quiz_answers = None

    # last quiz grading result (list of 0/1)
    if "user_results" not in st.session_state:
        st.session_state.user_results = []

    # detected emotion string
    if "current_emotion" not in st.session_state:
        st.session_state.current_emotion = None

    # speaking tab transcript cache
    if "last_transcript" not in st.session_state:
        st.session_state.last_transcript = None

    # chatbot tutor instance
    if "tutorbot" not in st.session_state:
        st.session_state.tutorbot = None

    # chat history for UI
    if "chat_history" not in st.session_state:
        st.session_state.chat_history = []
